### ISSUE TITLE
File missing when run

### ISSUE THREAD

**Issue by ghost** [fookatchu/SL1toPhoton#6]
In Ubuntu 18
```
$ python SL1_to_Photon.py test.sl1
Traceback (most recent call last):
  File "SL1_to_Photon.py", line 79, in <module>
    sl1.extract_images(tmpdirname)
  File "SL1_to_Photon.py", line 39, in extract_images
    with open(os.path.join(dirpath, filename), 'bw') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpy06zo06b/thumbnail/thumbnail400x400.png'

```
I installed its own venv:
```
(venv) $ pip install -r requirements.txt
Requirement already satisfied: numpy>=1.16.2 in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: Pillow>=6.0.0 in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: pyphotonfile>=0.1.1 in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: PySide2>=5.12.2 in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: shiboken2==5.14.1 in ./venv/lib/python3.6/site-packages (from PySide2>=5.12.2->-r requirements.txt (line 4))

```

**Comment by fookatchu** [comment]
Can you share the sl1 file or the version of PrusaSlicer used? It looks like its linked to the recently added thumbnail feature.

**Comment by ghost** [comment]
I attach a minimal file [untitled.zip](https://github.com/fookatchu/SL1toPhoton/files/4398752/untitled.zip). It is exported by 
PrusaSlicer-2.2.0+linux-x64-202003211856.

**Comment by fookatchu** [comment]
Should be fixed now. As I expected, this was due to the new thumbnail images beeing saved in the sl1-file. Can you please verify that it works for you?

**Comment by ghost** [comment]
It works now. Verified on different files. Thanks!
